### ISSUE TITLE
Issue with Bokeh and interactive classifier

### ISSUE THREAD

**Issue by ebbestubbe** [koaning/human-learn#84]
I was following the calmcode.io draw tutorial here
https://calmcode.io/human-learn/draw.html

Working with Bokeh was a bit clunky(did not work in vscode or firefox, and it was quite slow in Chrome), but I did end up getting the json of the `hulearn.experimental.interactive.InteractiveCharts` object.
attached here: [penguin_draw.json](https://github.com/koaning/human-learn/files/13812002/penguin_draw.json)
In the fitting/drawing part of the demonstration, `preds = model.fit(X, y).predict_proba(X)` I get this error:

```
Traceback (most recent call last):
  File "C:\Users\stubb\AppData\Local\Temp\ipykernel_22968\2726856544.py", line 9, in <module>
    preds = model.fit(X, y).predict_proba(X)
  File "C:\repos\titanic\venv\lib\site-packages\hulearn\classification\interactiveclassifier.py", line 148, in predict_proba
    hits = [
  File "C:\repos\titanic\venv\lib\site-packages\hulearn\classification\interactiveclassifier.py", line 149, in <listcomp>
    self._count_hits(self.poly_data, x[1].to_dict()) for x in X.iterrows()
  File "C:\repos\titanic\venv\lib\site-packages\hulearn\classification\interactiveclassifier.py", line 109, in _count_hits
    point = Point(data_in[c["x_lab"]], data_in[c["y_lab"]])
KeyError: 'bill_length_mm'
```
This is my environment. I couldn't find a requirement file for the examples provided, so I had to install the packages by the latest versions(as instructed in the examples)
[reqs.txt](https://github.com/koaning/human-learn/files/13812037/reqs.txt)

(Btw thanks for a quick fix on the last issue, I was too slow to submit my own PR over the holidays :) )

**Comment by koaning** [comment]
It might be that there's an issue related to the Bokeh upgrade a year ago. I think there were some breaking changes from v1 -> v2.
